export const ROUTES = {
  AUTH: {
    LOGIN: `/login`,
    SIGNUP: `/signup`,
    RESET_PWD: `/reset-password`,
    SET_NEW_PASSWORD: `/set-new-password`,
    ADMIN_LAYOUT:`/admin`,
  },
  DASHBOARD: `/dashboard`,
  COLLECTIONENTRY: {
    VLC_COLLECTION_ENTRY: `/dashboard/collectionentry/vlc-collection-entry`,
    FARMER_COLLECTION_ENTRY: `/dashboard/collectionentry/farmer-collection-entry`,
    DISPATCH_ENTRY:`/dashboard/collectionentry/dispatch-entry`
  },
  COLLECTION:{
    VLC_COLLECTION:`/dashboard/vlc-collection`,
    BMC_COLLECTION:`/dashboard/bmc-collection`,
    CHILLING_CENTER:`/dashboard/chilling-center`,
    FARMER_MANAGEMENT:`/dashboard/farmer-management`,
  },
  MASTER:{
    ADD_FARMER:`/dashboard/add-farmer`,
    ADD_RATECHART:`/dashboard/add-rate-chart`,
    BONUS:`/dashboard/bonus`,
  },
  BILLING:{
    FARMER_DEDUCTION:`/dashboard/farmer-deduction`,
    GENERATE_BILL:`/dashboard/generate-bill`,
    PAYMENTANDRECEIPT:`/dashboard/payment-and-receipt`,
    VLC_COMMISSION_ENTRY:`/dashboard/vlc-commission-entry`,
    VLC_TS_ENTRY:`/dashboard/vlc-ts-entry`,
  },
  REPORTS:{
    FARMER_BILL_INVOICE_REPORT:`/dashboard/farmer-bill-invoice-report`,
    FARMER_COLLECTION:`/dashboard/farmer-collection`,
    CATTLE_FEED_FARMER_WISE_REPORT:`/dashboard/cattle-feed-farmer-wise-report`,
    CATTLE_FEED_SALES_REPORT:`/dashboard/cattle-feed-sales-report`,
    CATTLE_FEED_STOCK_REPORT:`/dashboard/cattle-feed-stock-report`,
    CATTLE_FEED_PURCHASE_REPORT:`/dashboard/cattle-feed-purchase-report`,
    FARMER_LIST:`/dashboard/farmer-list`,
    FARMER_PASSBOOK:`/dashboard/farmer-passbook`,
    PAYMENT_SUMMARY:`/dashboard/payment-summary`,
    PL_STATEMENT:`/dashboard/pl-statement`,
    RATECHART_REPORT:`/dashboard/ratechart-report`,
    REMAINING_BALANCE:`/dashboard/remaining-balance`,
    SHIFT_REPORTS:`/dashboard/shift-reports`,
    TOTAL_COLLECTION_REPORT:`/dashboard/total-collection-report`,
    VLC_COMMISSION_REPORT:`/dashboard/vlc-commission-report`,
    VLC_DIFFERENCE_REPORT: `/dashboard/vlc-diffrerence-report`,
    BANK_SUMMARY:`/dashboard/bank-summary`,
    BONUS_REPORT:`/dashboard/bonus-report`,
  },
  SETTINGS:{
    GENERAL_SETTINGS:`/dashboard/general-settings`,
    CATTLE_FEED_STOCK:`/dashboard/cattle-feed-stock`,
    PASSWORD_MANAGER:`/dashboard/password-manager`,
    SIDEBAR_ACCESS:`/dashboard/sidebar-access`,
    CREATE_USER:`/dashboard/create-user`,
  },
  SHUBHAM_MILK_PRODUCT:`/dashboard/shubham-milk-product`,
  GROUP_CATTLE_FEED_STOCK:`/dashboard/group-cattle-feed-stock`,
  FARMER_PAYMENT:`/dashboard/farmer-payment`,
  DYNAMIC_BILL_CYCLE: `/dashboard/dynamic-bill-cycle`,
  PROFILE:`/dashboard/profile`,
  AVATAR_SELECTOR:`/dashboard/avatar-selector`,
  ADMIN_DASHBOARD:`/admin/admin-dashboard`,
  ADMIN_CREATE_USER:`/admin/create-user`,
  ADMIN_CREATE_ADMIN:`/admin/create-admin`,
  ADMIN_MASTER:{
    MOBILE_APPLICATION:`/admin/mobile-application`,
    WEB_APPLICATION:`/admin/web-application`,
    FARMER_APPLICATION:`/admin/farmer-application`,
    ADD_BRANCH:`/admin/add-branch`,
    UPLOAD_RATE_CHART:`/admin/upload-rate-chart`,
    SIDEBAR_ACCESS:`/admin/sidebar-access`,
  },
  ACTIVATION:{
    ACTIVATION:`/admin/activation`,
    WEB_APPLICATION_ACTIVATION:`/admin/web-application-activation`,
  }
};
